'''
############################################################################
##                         GRETA REPOSITORY                               ##
############################################################################

repository name: Greta
repository version: 1.0 
repository link: https://github.com/jim-schwoebel/greta
author: Jim Schwoebel 
author contact: jim@protea.earth
description: Greta is an open-source voice assistant to help reduce your carbon footprint.
license category: opensource 
license: Apache 2.0 license 
organization name: Protea.earth 
location: Boston, MA
website: http://protea.earth 
release date: 2019-09-26

This code is hereby released under a Apache 2.0 license license. 

For more information, check out the license terms below. 

##############################################################################
##                            LICENSE TERMS                                 ##
##############################################################################

Copyright 2019 Protea.Earth

Licensed under the Apache License, Version 2.0 (the "License"); 
you may not use this file except in compliance with the License. 
You may obtain a copy of the License at 

     http://www.apache.org/licenses/LICENSE-2.0 

Unless required by applicable law or agreed to in writing, software 
distributed under the License is distributed on an "AS IS" BASIS, 
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
See the License for the specific language governing permissions and 
limitations under the License. 

##############################################################################
##                          PURCHASE_PRODUCT.PY                             ##
##############################################################################

This script 	Selects a random green vendor and an item that you could purchase 
to be a good environmental citizen (energy, tech, home, and fashion categories).

references:
--> https://www.onyalife.com/eco-friendly-products/#Clothing
--> https://theworldpursuit.com/list-of-eco-friendly-products/
--> https://www.budgetdumpster.com/blog/19-everyday-eco-friendly-products/
'''
##############################################################################
##                           IMPORT STATEMENTS                              ##
##############################################################################

import random, os, sys, json, datetime

##############################################################################
##                            HELPER FUNCTIONS                              ##
##############################################################################

def get_date():
    return str(datetime.datetime.now())

def speaktext(hostdir,text):
    # speak to user from a text sample (tts system)  
    curdir=os.getcwd()
    os.chdir(hostdir+'/actions') 
    os.system("python3 speak.py '%s'"%(str(text)))
    os.chdir(curdir)

##############################################################################
##                            MAIN SCRIPT                                   ##
##############################################################################
    
hostdir=sys.argv[1]
os.chdir(hostdir)

# pick type of product you'd like to explore further?
clothes_items={'http://recoverbrands.com/store/category/recoverproducts/':'Recover’s Range of Recycled Apparel made from recycled fabric', 
               'https://www.allbirds.com/':'Check Out Allbirds’s line of wool shoes for men and women, made in Korea with clean energy.'}

food_items={'https://uncommoncoffeeroasters.com/about/':'With this simple product, you can enjoy the convenience of single-serve coffee pods without the waste. Uncommon Coffee Roasters created the first 100 percent compostable pod on the market, using plant-based materials that will completely biodegrade within just 90 days in your compost pile. Even their packaging is green — featuring a 100 percent recyclable outer box and a compostable inner sleeve.'}

fashion_items={'https://www.greengurugear.com/collections/travel-accessories':'Support the removal and repurposing of landfill rubber by using any of these travel pouches made from recycled bike tubes by Green Guru Gear. Carry your belongings safely while helping the environment at the same time.',
               'https://www.onyalife.com/product/backpack/':'Our lines of stylish backpacks are made from rPET (Recycled Polyethylene Terephthalate) — the material created when old plastic water bottles are recycled into fibre. Each of our backpacks scrunches down into a keyring size, which makes them great for school or traveling.',
               'https://www.we-wood.com.au/':'WeWood watches are made from 100 percent recycled timber, including Indian rosewood, mahogany, coffee tree and teak. They are completely free from any toxic chemicals, and not a single tree is cut down in their manufacturing. In fact, for every watch you buy they will plant a tree.',
               'http://www.iwantproof.com/collections/wood-collection':'There are few better ways to look good and reduce your plastic pollution than with a stylish pair of wooden sunglasses. Proof Eyewear manufactures handcrafted wooden sunglasses from sustainable materials, including FSC-certified wood, cotton-based acetate, and repurposed skateboard decks.',
               'http://www.doamore.com/ethical-rings/':'Do Amore creates “ethical rings.” Every ring bought gives two people clean water for life by co-founding a water well in a developing country. Their rings are made from recycled precious metals that are conflict free — part of the No Dirty Gold campaign.',
               'https://www.sea2see.org/':'Sea2see collects ocean plastic waste, nets, and ropes in coordination with fishing communities in Spain to create their Italian designed eyewear. Collecting an average of 1 ton of plastic waste every second day, selected plastic waste is used as the raw material for their eyeglasses with the remaining waste sold off to other companies for use in different processes.',
               'https://www.rareform.com/':'Over 600,000 tons of non-recyclable vinyl from billboard banners alone finds its way to landfills each year. RAREFORM took note and rescues this durable material to create one of a kind wallets and other products, including bike bags, iPhone cases and more.',
               'https://mothererth.com/':'Mother Erth weaves eco conscious fashion and women’s empowerment together by repurposing factory-reject plastic headed for the landfill into eco-friendly products. These handmade bags and accessories are woven from discarded plastic laminated foil that was rejected due to printing defects. Instead of ending up in landfills or reaching waterways, Mother Erth intercepts it and prepares it for new life in the form of unique and colorful handbags, clutches and more.',
               'https://theworldpursuit.com/product/B07MT9Z8T5/US/':'These makeup pads are a perfect go green biodegradable product and are ready to reuse over and over again. The set of 14 is made out of organic bamboo fibers and come with a high-quality small laundry bag to wash these. Save money over time by not buying cotton pads and save the environment!',
               'https://theworldpursuit.com/product/B000JEXG8U/US/':'Rainbow Sandals create strong, quality footwear that won’t end up in a landfill. I’ve only had two pairs in my life. I’ll be getting a third, but not because they didn’t hold up, but because they were stolen from under my seat in Thailand and then again a dog ran away with my flops years later in Nusa Lembongan.',
               'https://yogademocracy.com/':'I never forget to bring clothes that are good to workout in when I travel. I always travel with yoga pants, sports bras, and breathable tank tops. One of my favorite brands to buy yoga pants from is Yoga Democracy. Yoga Democracycarries yoga pants that have fun designs, yet they are still extremely durable. All their gear is made from recycled nylon from material like a fishing net that does great damage to our oceans. It’s estimated that there over 600,000 tonnes of this fishing net litter is going into our oceans, so wearing Yoga Democracy is choosing to fight against that and use eco-friendly materials. They are eco-friendly, USA made, and sweatshop free! To provide an update to this post we recently found out that polyester clothes are often credited for micro-plastics in the ocean. This hasn’t been totally confirmed, but it’s definitely something to keep in mind when purchasing products and hopefully purchase more eco friendly clothing. Use the code TWP20 for 20 percent off your purchase.',
               'https://www.fairindigo.com/':'Fair Indigo sources organic Pima cotton from small family farms in Peru. I love buying clothing that is sourced ethically from workers making a fair wage – not sweatshops. They use Peruvian cotton and alpaca because it is ultra soft, and you can feel it with these clothes. I chose some very simple black, navy, and grey skirts and dresses as Fair Indigo uses only certified earth-friendly dyes. Now, it just has to get warm enough in the mountains that I can wear them – yes, it still feels like early Spring here.',
               'https://www.amazon.com/stores/Jelt/Jelt/page/2CB224E9-C047-4EDA-9FC2-6E5E6C4CD929/':'Unless I am hiking in leggings I need a belt to secure my pants. The newest one I just got is a Jelt Belt. Jelt is a women-owned social enterprise that produces belts made from 100 percent recycled plastic bottles with an innovative patented flat buckle that won’t show a bump under tops or tees. Both Cameron and I have a few of these bad boys and they are SO much better than regularly clunky belts.',
               'https://ecovibeapparel.com/':'With EcoVibe Apparel, you can dress stylishly without causing ecological harm. From tees to dresses, EcoVibe creates each of their pieces as completely as possible from sustainable fabrics. For example, modal is a material made from beech pulp that can be extracted without cutting down the tree. The resulting fabric is CO2-neutral, stain-resistant, and extremely durable. Other fabrics used in their offerings, such as Tencel, are fully biodegradable.'}

home_items={'https://www.hydroflask.com/':'reuseable bottles to reduce plastic use.',
          'http://au.whogivesacrap.org/': 'recycled toilet tissue with one hundred percent recycled paper fibres, bamboo or sugarcane. This saves water, trees, and reduces carbon emissions. They also donate a whopping 50 percent of their profits to WaterAid to build toilets for those in need.',
          'https://www.vivaterra.com/recycled-sari-table-linen-collection.html':'This table linen collection from Viva Terra is handmade in India by artisans who carefully collect pieces of vintage and upcycled fabrics to create elaborate patterns and colors. Each piece is different from the next because they are each hand sewn from the scraps leftover during the process of hand making Indian saris.',
          'https://www.onyalife.com/product/disposal/': 'Do you have a dog at home? If you do, you probably go through quite a few waste bags each month taking him or her on walks. Our disposal bags come with 25 waste bags that are biodegradable and disposable. So while your pet is creating waste, you don’t have to.',
          'https://www.onyalife.com/product/sandwich-wrap/':'Packed school lunches may seem innocent enough, but when you multiply them by each student at your child’s school and each school in your country, the amount of single-use plastic waste adds up quickly. Our reusable sandwich wraps (made from recycled PET bottles) can completely eliminate the plastic pollution produced from your child’s lunch or anytime you use single-use sandwich wraps.',
          'https://fabhabitat.com/rugs/material/recycled-plastic.html': 'Woven from premium quality recycled plastic drinking straws, the beautiful and affordable recycled plastic rugs from Fab Habitat make several statments at the same time. Available in a wide range of colors, patterns and designs, plastic straws have never looked so good.',
          'https://bhumi.com.au/collections/towels': 'Bhumi has made some fantastic fair trade products. Their organic towels, made from cotton grown and picked with sustainable farming methods, are no exception.',
          'http://www.amazon.com/Pilot-B2P-Retractable-Recycled-Bottles/dp/B007ZYF37O/': 'Water bottles are one of the top contributors to not only plastic pollution, but to world pollution in general. You can support removing some of those bottles from landfills by purchasing these ballpoint pens from Pilot.',
          'https://bhumi.com.au/collections/organic-cotton-bedding': 'Bhumi is back at it again with another selection of awesome organic products: Bedding. They have a huge variety of bedding options all sourced from sustainably farmed cotton and responsibly manufactured.',
          'http://www.greenlinepaper.com/office-paper-envelopes/multipurpose-paper.html':'GreenLine Paper Company has done a great job creating products from recycled materials. Their multipurpose paper is recycled from paper itself, helping preserve those trees’ value for a little longer.',
          'http://www.trex.com/why-trex/eco-friendly-decking/': 'Trex makes eco friendly composite decks that are made from 95 percent recycled wood and plastic film. They also use Earth-friendly manufacturing processes, like reclaiming factory waste and eliminating the use of harmful chemicals.',
          'http://www.rubbercal.com/rubber-flooring/eco-friendly-flooring/':'These Rubber Cal floor mats are made from natural, reclaimed, or recycled rubber material. Due to their high durability, they’re great for areas such as garages, warehouses, and porches.',
          'https://www.ifyoucare.com/baking-cooking/recycled-aluminum-foil/':'Aluminium foil is one of the most used home items. If You Care produces a line of aluminium foil that’s made from 100% percent recycled aluminium. Their foil takes 95 percent less energy to produce than traditional foil manufacturing.',
          'http://madebyradius.com/products/the-source?variant=1538366340':'To reduce plastic waste in your toothbrushes, try out this brush with a handle made from repurposed materials (the material varies). By using these toothbrushes, RADIUS claims you can reduce waste by 93 percent (the head must be replaced every once in a while).',
          'https://www.amazon.com/Souldier-GS0000BK04BK-Recycled-Seatbelt-Electric/dp/B00C4VYDS8':'Do you like to jam out? How about using a sustainable guitar strap to help out the environment as well? This strap is made from a recycled seatbelt, and it doesn’t look half bad.',
          'https://www.amazon.com/Reusable-Food-Pouch-Refillable-Containers/dp/B01CC4P8XU': 'Healthy Planet Solutions has developed an alternative to traditional baby food containers — a reusable baby food pouch. It’s easy to fill and clean, and it is dishwasher, boil, and freezer safe.',
          'http://www.greentoys.com/shop-page':'Green Toys is a fantastic company. They manufacture and sell toys made from 100 percent recycled materials — milk jugs being the primary material. They also use plastic recycled from other types of products. Their toys surpass U.S. and international standards for BPA and Phthalates.',
          'https://www.earthled.com/':'LED bulbs can do wonders for conserving energy. EarthLED sells a wide range of LED bulbs to replace your high-energy incandescent, fluorescent and halogen bulbs.',
          'https://www.waterpik.com/shower-head/products/ecoflow/':'You can conserve a lot of wasted water with one simple change: Use a low-flow shower head. This low-flow shower head from EcoFlow will help you save water, save money, and it meets EPA WaterSense® performance standards.',
          'http://www.greenhousemegastore.com/product/western-pulp-square-pots/biodegradable-pots':'Help keep your garden safe from plastic and rubber pollution with these Western biodegradable garden pots. They’re made from recycled material and decompose in about a year.',
          'http://www.leafware.com/shop-leafware#!/Cutlery/c/12982162/offset=0&sort=normal':'Plastic cutlery is almost always used once and thrown away. Parties, BBQs, or school lunches can produce a lot of plastic cutlery waste. Reduce or eliminate this waste by using Leafware compostable forks, spoons, knives and tasters.',
          'http://www.sustyparty.com/collections/plates':'Just like plastic cutlery, plastic and paper plates are almost always used once and thrown away. Parties, BBQs, or school lunches can produce a lot of plastic and paper plate waste. Reduce or eliminate this waste by using compostable party plates.',
          'http://www.leafware.com/shop-leafware#!/Bowls/c/12982160/offset=0&sort=normal':'Instead of putting party, BBQ, or camping snacks in a plastic or paper bowl, you can use a compostable bowl that’s both human and environmentally friendly.',
          'https://ecoture.com.au/collections/umbrellas-womens':'An umbrella that’s stylish, hardy and biodegradable, the BRELLI is perfect, rain or shine. It offers superior protection from the rain, blocks UVA and UVB rays, and withstands winds up to 40 mph / 64 kpm. Each BRELLI is unique, handmade by expert craftspeople from sustainable materials and 100% biodegradable PVC plastic.',
          'https://www.onyalife.com/product/reusable-produce-bag-8pack/':'Onya award winning reusable produce bags are some of our most popular products. Instead of using the produce bags from the grocery store and throwing them out when your food is consumed, you can use these reusable ones and never throw away a plastic produce bag again. They also let water and air through, so you can wash your fruits and veggies within the bags before popping them in the fridge.',
          'https://www.onyalife.com/product/shopping-bag-large/':'Plastic shopping bags from the grocery store (or any retail store) produce even more waste than produce bags. A reusable shopping bag can be used to carry your groceries and other items, which eliminates your plastic waste from shopping bags every time you shop.',
          'https://www.onyalife.com/product/reusable-bread-bag/':'Carry your bread home in style without any packaging waste. Our reusable Bread Bag is made from up to 10x recycled plastic drink bottles and is designed to replace single use paper or plastic bread bags, plastic toggles and ties. Perfect for the home baker too. Bread stored in one of our bread bags can last up to 3 months in a frost free freezer and will not sustain freezer burn due to the unique double lining and airtight roll and lock closure.',
          'https://www.onyalife.com/product/reusable-bulk-food-bag-set/':'Our reusable bulk bags were designed to help people easily and conveniently transport their bulk food purchases home. The bags have been designed as a lightweight top up tool to replace the need for carrying jars and canisters when doing your shopping. Our bulk food bag range includes a large, medium and small bulk food bag along with our specially designed bulk food shopping tote. We love diverting existing waste from landfill which is why our bulk food bags are made from BPA free, food safe recycled plastic drink bottles.',
          'https://anindilyakwaarts.com.au/shop/':'When plastic fishing nets are lost or thrown away, they can drift through the ocean like ghosts – these ‘ghost nets’ are not only another form of plastic littering the ocean, they are deadly as they catch and kill marine life. Artists from Anindilyakwa Art Centre in Australia’s far North collect ‘ghost nets’ that wash up on their local beaches. Using their traditional weaving skills and integrating colourful fabrics that they dye themselves, the artists create beautiful baskets that put the plastics right back to work, while helping call attention to the problem of ghost nets.',
          'https://www.onyalife.com/product/compostable-bin-liners-30l//':'Unlike some other bags on the market, our bags are CERTIFIED compostable to Australian, European, USA & Japanese standards, which means they have been independently assessed to break down to virtually undetectable levels in the soil and are deemed “worm safe” with no micro plastic residues left behind. Our compostable bin liners are available in 4 sizes (8L, 30L, 36L and 60L) and are made from 100 percent GMO free renewable plants and are free from any plastic additives such as Polypropylene, Polyethylene, Polystyrene & PVC.',
          'https://www.houseology.com/':'Fancy sitting in your backyard or garden in an eco friendly way? This practical and stylish Recycled Plastic Lounge Chair is a great choice for enjoying time outdoors. It’s a modern update to the traditional Adirondack chair and even better, there is no seasonal maintenance required. Available in four colors, the recycled plastic lounge chairs from Houseology are made from 312 reclaimed plastic milk jugs.',
          'https://theworldpursuit.com/product/B00MEL8BUO/US/':'Reusable Bamboo Utensil - This silverware is heat resistant, small, and lightweight making it the perfect environmentally friendly travel accessory. These eco friendly utensils have saved us during those random times when we desperately need a spoon or fork to eat too.',
          'https://www.amazon.com/Humangear-GoToob-3-Pack-Large-Clear/dp/B002VS8H3G/':'Don’t lug around a full sized body wash container, put liquids in little travel bottles instead! GoToob bottles are made with durable silicon that are food safe and airplane carry-on approved. Of course, they are 100% BPA free and also a great eco friendly gift idea.',
          'https://theworldpursuit.com/list-of-eco-friendly-products/#':'As metioned I love Humangear products especially the GoTubb. When I first got these I had no clue what I would actually do with them and actually considered returning them. Six months later and the truth is I use these on every.single.trip. They are great to have for all those little things that you never know what to do with on travels. I’m talking things like bobby pins, earrings, keys, and now I store a few pairs of earbuds in them for the plane. Even if you don’t know what you need them for immediately I promise they are a great eco alternative to plastic bags.',
          'https://theworldpursuit.com/product/B008EADHTO/US/':'Never ever pick up a plastic cup again with the GoCup. This thing is so perfect for traveling, hiking, and on a long haul flight. It’s compact, made from FDA food grade silicone, and a fitted lid with an integrated pill container should you need medication.',
          'https://theworldpursuit.com/product/B01N4E5MW4/US/':'We have a few of these because we absolutely love coffee and tea. Although we make a lot of our own coffee we do have the occasional $5 cappuccino. This escalates when we travel and we usually have a cup of coffee a day. I hate those plastic lids given out and this is the best alternative to a wasteful plastic lid. Plus I love drinking off the silicone top.',
          'https://www.hydroflask.com/tumblers':'The Hydroflask coffee tumbler was the first travel coffee thermos we ever invested in. It’s one of the best-insulated coffee mugs out there and continues to remain the favorite that we have in the cupboard.',
          'https://theworldpursuit.com/product/B004TN51EE/US/':'I love traveling with my Aurorae mat for yoga sessions on the road. They are my absolute favorite eco friendly yoga mat. All their mats are made from a non-toxic resin free from Phthalates, Phenols, PAHS, Latex, Rubber and Silicon. On top of that, they are biodegradable, hypoallergenic, and made from eco-safe patented PER. These yoga mats are ¼”  thick so definitely not as small or compact as the Manduka.',
          'https://theworldpursuit.com/product/B07FL946Z7/US/':'I have to floss my teeth all the time and sometimes even have to travel around with a spare string of floss in my backpack. I bet you never thought about it, but floss is usually plastic. It’s also toxic and coated with PFC’s (harmful chemical) that make the gloss glide better. These chemicals have even been linked to dementia, cancer, and thyroid disease – yikes! So I had to mention silk floss on this list of eco friendly products used in daily life. A good way to avoid all the chemicals and plastic waste is with flossing alternatives like this one.',
          'https://www.amazon.com/Scrubba-Portable-Laundry-System-Wash/dp/B00BUI7HFC/':'Washing your clothes while traveling is never fun. That’s why we were super pumped to get the Scrubba. Which is a tiny and lightweight mobile laundry machine. Just put your dirty clothes in the bag, add water and soap, seal and scrub away. Now you can literally wash your clothes anywhere there is water. Although, the Scrubba retails for just around $50, think about how much money washing your clothes can cost in a hostel, hotel, or laundromat. We usually pay about $5 per load. So you will easily make your money back after just 10 loads of wash. Most importantly this eco-friendly product uses less water than a commercial washing machine and no energy. I also found that this is another fantastic eco-friendly gift idea for travelers and hikers.',
          'https://theworldpursuit.com/product/k-alaffia/US/':'It doesn’t end there though. Alaffia empowers and employs women from rural Togo and pays them a real and fair wage and run a number of empowerment projects. This includes reforestation projects, education projects, maternal care projects, and FMG (female genital mutilation) projects. In case you needed another reason to buy from them, they’ve also planted more than 60,000 trees since 2003.',
          'https://theworldpursuit.com/product/k-Ethique+Eco-Friendly+Solid+Face+Cream/US/':'Ethique makes some of the best eco-friendly skincare products on the market right now.  Ethique has a wide range of toiletry products ranging from shampoo to face cream. All of their products use natural and organic ingredients and use completely eco-friendly packaging on their products. Oh, yea it doesn’t hurt that this small business was started by a woman and every product is Cruelty-Free, TSA Friendly, and Compostable. There are 80 billion shampoo and conditioner plastic bottles thrown out every year and they all make their way to the ocean. By purchasing one bar from Ethique you are saving three plastic bottles from ending up in a landfill.',
          'https://www.amazon.com/Planet-Reusable-Grocery-Shopping-Bags/dp/B00H22NF1U/':'In today’s day and age, I feel like this is kind of a duh eco-friendly product. If you could help reduce waste on the planet by simply bringing your own bag to the grocery store would you? Of course! These bags are cute, reusable, and pack up nicely. These aren’t just good for being eco-friendly at home either, but for traveling with just about anything in general.',
          'https://theworldpursuit.com/product/B07BMHRL6Z/US/':'Skin cancer is for real! Not having sun protection can lead to sunburn and in the long term skin cancer/skin aging. You will spend a lot of time outside when you travel and therefore under the sun. We highly recommend getting an eco friendly sun cream that does not contain harmful chemicals. Once you go into the ocean those harmful chemicals from your sunscreen will run off and ruin the coral and marine life so it’s super important to sunbath responsibly. Eco-friendly sunscreen is mineral based and usually only cost a few dollars more to help protect our natural bodies of water. If you’re not going to swim and only sunbathe just go with a reliable name brand — granted runoff often still ends in our oceans and lakes.',
          'https://www.rei.com/product/898532/packtowl-luxe-towel':'We always recommend bringing a travel towel when you’re on the road. They pack up small, antimicrobial, and are lightweight so they will save you from always needing a new towel or from constantly washing yours. The biggest complaint about travel towels is that they often feel nothing like the plush cotton towels we are accustomed to at home and in hotels. However, with the PackTowl you can forget about all of that because they set out to create a towel that mimics its cotton counterparts with the technical features of a travel towel.',
          'https://theworldpursuit.com/product/B000FAG6X0/US/':'Ladies, have you heard of the diva cup yet? It’s one of those new eco friendly travel products that may change your life. This 100% silicone piece will completely eliminate tampons out of your life. Which means you can eliminate those plastic applicators. Yes, the DivaCup is a reusable menstrual cup that collects menstrual flow and offers 12 hours of protection. It’s odor free, comfortable, and definitely saves you money on buying tampons over time.',
          'https://theworldpursuit.com/product/B079VJSFCK/US/':'Ditch the disposable razors and get your hands on a proper razor with sharp blades. You get a much closer shave with these types of razors anyway, aluminum is much easier to recycle, and most importantly, you’re not throwing away a plastic razor every three days.',
          'https://www.bogobrush.com/':'You might not think oral hygiene can help the environment but Bogobrush begs to differ with their two innovative toothbrushes. Their recyclable brush is made from recycled #5 plastic and can be dropped right back into your curbside recycling bin when you’re done with it. They also offer a biodegradable toothbrush made from bioplastic. Once the brush wears out, simply throw it in the compost pile. Besides cutting plastic pollution, Bogobrush donates a toothbrush to the needy for every one sold, and all their products are made in the U.S., providing jobs in four different cities.',
          'http://riversoap.com/products/':'River Soap brings you a greener clean with bar soap that’s 100 percent natural, cruelty-free and biodegradable. Each bar starts with a palm and coconut oil base, using essential oils for fragrance, and spices and botanicals for color. Except for their “Milk & Honey” bars, all of their products are suitable for vegans and even their packaging is made from 100 percent recycled cardboard to create a product that’s truly green from start to finish.',
          'http://www.highsierrashowerheads.com/':'Our daily showers can waste an incredible amount of water, but High Sierra’s innovative take on low-flow technology is here to change all that. Their nozzles use 40 percent less water than even other low-flow showerheads, without the clogging problems that often accompany them. And for people with septic systems, High Sierra’s technology often gives better water pressure than conventional nozzles. This is another eco-friendly product made here in the U.S., so you can feel good about supporting local jobs while you reduce your water footprint.',
          'https://www.sheamoisture.com/products/hair.html':'Shea Moisture’s line of hair products keeps our water supply clean with shampoos, conditioners, mousses and dyes that contain none of the petroleum, parabens and other harmful chemical usually found in other products. Instead, they use all natural, organic ingredients that are sustainably produced, fairly traded and never tested on animals. Shea Moisture has been creating healthy, eco-friendly products since 1912, when it began life as a one-woman home-based business in Bonthe, Sierra Leone. Today, the company supports minority women-led businesses through its Community Commerce program.',
          'http://greenforestpaper.com/':'The bathroom is — pun absolutely intended — a pretty wasteful place. But it doesn’t have to be. Green Forest Paper’s toilet paper and tissues are made entirely from recycled paper —even the cardboard rolls are 100 percent recycled. They don’t use toxic bleach for whitening, and since recycled paper has shorter fibers, it breaks down faster in septic systems. Green Forest Paper’s environmental cred even extends to the outer packaging of their products, which can be dropped off anywhere you recycle plastic grocery bags.',
          'https://www.beeswrap.com/':'Vermont-based Bee’s Wrap is here to greenify your kitchen with reusable wraps made from organic cotton coated with a mixture of beeswax, tree resin and organic jojoba oil. The heat from your hands allows you to mold a wrap to whatever you need to store, from a plate of baked goods to a sandwich for your lunchbox. When you’re done with it, a quick rinse in cool water with a little dish soap will have it ready for reuse again and again!',
          'https://fullcirclehome.com/collections/compost':'If you’ve already started composting , the kitchen bins at Full Circle will make collecting your scraps much easier. Each bin is small enough to fit right on your kitchen counter so it’s always in reach as you’re chopping veggies or cleaning up after a meal. And you won’t have to worry about odor — these bins are designed to allow air flow so that scraps begin decomposing without any funk.',
          'http://www.gogreenlunchbox.com/':'Multiple plastic baggies, juice boxes, snack wrappers—if you’re worried by the amount of packaging involved in your kids’ lunches, Go Green Lunch Box is an ingeniously green product featuring compartments large enough to hold a variety of lunchtime favorites in place without packaging. A “turn ‘n lock” lid keeps everything fresh. You can even buy sets that come with a fun carrying case, ice pack and reusable drink bottle. When you no longer need them, each box can be recycled.',
          'https://www.kleankanteen.com/collections/all':'Klean Kanteen created the original stainless steel water bottle back in 2004 and today you can turn to them for whatever liquid you need to tote. Whether it’s an insulated tumbler to keep your morning coffee hot or a growler for your favorite beer, you’ll find sleek containers made from long-lasting, food-safe stainless steel you can reuse for years. Even better, many of their lid types are interchangeable, so you can buy one or two bottles but switch out the lids to use them in different ways.',
          'http://www.lilywrap.com/#home/products-page':'If presentation is as much a part of your gift-giving as the present itself, Lilwrap is the eco-friendly product you need to create beautifully wrapped packages the green way. Their gift pouches are made of stretchy fabric which can expand to fit nearly any object, all tied up with a classic bow. Available in a huge variety of fun prints, this fabric is durable enough to last through countless gift-giving occasions, and can be quickly hand-washed if it ever gets dirty.',
          'http://www.mollyssuds.com/product/100-wool-dryer-balls-set-of-3/':'We all want our clothes to be soft and comfy, but most fabric softeners are a cocktail of chemicals that aren’t safe for the environment and may be unhealthy for humans too. That’s why Molly Suds created a reusable wool dryer ball to soften clothes naturally. A single three-pack will easily see you through 1000 loads. That’s about three years’ worth of laundry, so not only will you be reducing your use of harmful chemicals, you’ll be saving money while you do it! And when your dryer balls finally do wear out, you can compost them. Molly Suds was created by a pediatric nurse concerned about mounting research that chemicals in our cleaning products can affect fetal development. Your own family can now enjoy the safer, greener products she created to keep her own family healthy.',
          'http://ecos.com/product-category/pet/':'Caring for your pets can get messy, but with Ecos’ line of pet supplies, you’ll find everything from stain and odor removers to cage cleaners formulated from sustainably sourced ingredients without any harmful chemicals, synthetics or dyes. Products like their pet wipes are biodegradable, while liquid cleaners are made safe for septic or grey water systems to prevent water pollution. On top of all that, Ecos manufactures their products using 100 percent renewable energy while diverting 95 percent of their waste from landfills.',
          'https://grabgreenhome.com/collections/laundry/Laundry':'With Grab Green’s line of eco-friendly laundry products, you can clean your clothes without dirtying our water supply. Their detergent pods and powders contain no dyes, chlorine, phosphates or phthalates — chemicals which can be harmful to the environment and in some cases may be unhealthy for humans too. To greenify the entire laundry process, you can also buy dryer sheets that can be reused for multiple loads, then composted when they wear out. Grab Green also works hard to use minimal, recyclable packaging and to source their materials sustainably.',
          'https://urbanclotheslines.com/':'Urban Clothesline makes it easy to air-dry your clothing no matter where you live or how much space you have to work with. From umbrella-style clotheslines you can set up in a big backyard to retractable models perfect for small spaces, Urban Clothesline merges time-honored technology with modern aesthetics to help you save both energy and money. In fact, you won’t just save on your electric bill: when they’re not being pummeled in a dryer every week, your clothes can go much longer without fading or showing wear.'}

plant_trees={'https://cowpots.com/':'Thanks to CowPots, gardeners’ thumbs are about to get a whole lot greener. After extracting methane to create green energy, dairy farmers Matt and Ben Freund turn their cows’ manure into planters that are not only 100 percent biodegradable but made almost entirely from a renewable resource. Just start your plants in a CowPot as you normally would, then transfer the entire pot into the ground when the time is right. Within a few weeks, the pot will biodegrade, giving your soil a powerful nutrient boost in the process.'}

tech_items={ 'http://www.iameco.com/iameco-3/overview/':'Iameco manufactures some pretty cool environmentally friendly gadgets. Their touch screen computer has a carbon footprint that’s 70 percent lower than the average personal computer. It’s also the first computer of its kind to win the EU Eco Flower certification.',
             'http://www.iameco.com/d4r/overview/':'This environmentally friendly laptop from Iameco was manufactured while decreasing greenhouse gas emissions by 30%, re-using 70 percent of the material, and reducing fresh water utilization by 75 percent.',
             'http://www.iameco.com/iameco-3/overview/accessories/':'Iameco also stocks a range of computer accessories (keyboards, mice, and cases) made from sustainable materials and responsibly manufactured.',
             'https://www.amazon.com/Vortex-LED-Dynamo-Crank-Flashlight/dp/B00QUSEDXG':'Instead of changing batteries each time your flashlight runs out of energy, try this flashlight from Vortex. It runs on a rechargeable battery that’s hand-cranked, saving multiple batteries per year from entering landfills.',
             'https://www.fairphone.com/':'Fairphone develops and sells a cell phone that’s revolutionizing the entire supply chain. They are integrating materials that support local economies, increasing the phone’s usable life, they only work with manufacturers that give their workers safe working conditions, and Fairphone makes their phones safe for reuse and recycling.',
             'https://revealshop.com/shop/eco-materials/bamboo/bamboo-solar-bluetooth-speaker-and-portable-charger.html/':'Reveal has a Bamboo Solar Bluetooth Speaker and Portable Smartphone Charger. Pleasing to both the ear and eye, Reveal’s dedication to sustainability shows itself in this amazing speaker design and they give back by planting a tree of for every product sold.',
             'https://grovemade.com/product/skate-back/':'Most iPhone backs and cases are made out of plastic. The backs from Grovemade are made out of discarded skateboard decks, and they look pretty cool, too.',
             'https://pelacase.com/':'There are now more mobile devices than there are people on earth. That’s a staggering amount of plastic phone accessories (and packaging) being consumed and disposed of at an alarming rate. From manufacturing to packaging, Pela hopes to displace waste and pollution in the tech accessory market with their 100 percent compostable sustainable bioplastic iPhone and Andriod phone cases.',
             'http://www.greentoys.com/shop-page':'Thanks to California-based Green Toys, you can give the environment a gift every time you buy one for your kids. From trucks to teething rings to tea sets, Green Toys creates playtime favorites using nothing but recycled milk jugs and earth-friendly dyes. And since they include no mixed materials, you can easily recycle them curbside when your kids outgrow them. As socially responsible as they are sustainable, Green Toys manufactures everything here in the U.S., so they can ensure worker safety and monitor their environmental impact.'}

energy_items={'https://www.oneearthdesigns.com/':'The SolSource Solar Powered Grill has been featured on programs like Top Chef, The Discovery Channel, and BBC. This grill uses reflections of the Sun’s rays to heat up a grilling platform suspended between the reflective areas. It can cook a meal in 10 minutes and the setup can be cleaned simply with water.',
              'http://www.husqvarna.com/us/products/robotic-lawn-mowers/':'This lawn mower by Husqvarna is powered the Sun’s energy. Not only that, it’s completely autonomous and cuts your lawn on its own.',
              'https://www.amazon.com/Solar-Go-ISB-RL01-Portable-Power/dp/B004IYJOFQ':'Solar-2-Go has developing a portable charging station that’s powered by solar power. It’s a great backup generator for the home or for long trips.',
              'http://www.sunrisesolar.net/':'Attics can get extremely hot and stuffy, especially in the summer time. To conserve energy and save money, try out one of SunRise’s solar powered attic fans.',
              'https://www.rei.com/product/124869/mpowerd-luci-outdoor-20-inflatable-solar-lantern?cm_mmc':'We love to travel and hike with a solar-powered lamp! We just got it a week ago and have already had to use it a number of times when we were low on light. This little device is a solar-powered lamp and is a completely environmentally safe product. It can be used on a table, hung around your neck, or attached to a bicycle. Five hours of sunlight will yield seven hours of bright illumination, and 24 hours of low illumination.',
              'https://www.amazon.com/Charger-Portable-Waterproof-Shockproof-Dustproof/dp/B00YOP7LV8/':'With this waterproof and dustproof solar panel charger, you will be able to stay charged and save energy at the same time.  This was the perfect earth-friendly product for our year-long road trip across Africa. When you’re camping or out in the wilderness as I’m sure you are aware, there are no outlets. This solar phone charger can handle charging my phone at least three times before I have to throw it in the sun again. Sometimes we even use it to charge two phones at once! It took me a while to invest in one of these bad boys, but now my camping/outdoor/adventure life has never been the same!'}


categories=[clothes_items, food_items, fashion_items, home_items, plant_trees, tech_items, energy_items]

# tell a random joke 
randomint=random.randint(0,len(categories)-1)
category = categories[randomint]
links=list(category)
link=links[random.randint(0,len(links)-1)]
description=category[link]

os.system('open %s'%(link))
speaktext(hostdir,description)

# update database
database=json.load(open('actions.json'))
action_log=database['action log']

action={
    'action':'facts.py',
    'date': get_date(),
    'meta': [link, description],
}

action_log.append(action)
jsonfile=open('actions.json','w')
json.dump(database,jsonfile)
jsonfile.close()
